# Generated by Django 5.0.6 on 2025-06-24 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('aluno_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('serie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('disciplina_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('escola_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('diagnostico_id', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(choices=[('Adequado', 'Adequado'), ('Alerta', 'Alerta'), ('Crítico', 'Crítico'), ('Não Avaliado', 'Não Avaliado')], default='Não Avaliado', max_length=20)),
                ('data_diagnostico', models.DateTimeField(auto_now=True)),
                ('detalhes', models.JSONField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='api.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('avaliacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='api.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('frequencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('bimestre', models.IntegerField()),
                ('faltas', models.IntegerField()),
                ('data_registro', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='api.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('turma_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='api.escola')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='api.turma'),
        ),
    ]
